spring.application.name=auth-service
server.port=8080

# Cấu hình PostgreSQL (thay username/password của bạn nếu cần)
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=postgres
spring.datasource.password=Matkhaumoi1@
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Config
jwt.secret=mySecretKey12345678901234567890123456789012
jwt.expiration-ms=3600000
jwt.refresh-token-expiration-ms=604800000

logging.level.org.springframework.security=TRACE
logging.level.com.example.auth_service.security=DEBUG

# ==============================
# Gmail SMTP
# ==============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.default-encoding=UTF-8

# Timeout
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

app.activation-url=http://localhost:8080/api/auth/activate?token=
