package com.example.auth_service.security;

/** Explicit permissions; adding a permission never grants it to a role automatically. */
public enum Permission {
    DEPARTMENT_MANAGE,
    PROFILE_READ, PROFILE_UPDATE,
    USER_READ, USER_MANAGE, ROLE_READ, ROLE_MANAGE, AUDIT_READ,
    CATALOG_READ, CATALOG_MANAGE, SALARY_READ, SALARY_MANAGE,
    REQUISITION_CREATE, REQUISITION_READ_OWN, REQUISITION_READ_ALL, REQUISITION_APPROVE,
    RECRUITER_ASSIGN, JOB_MANAGE,
    APPLICATION_CREATE, CANDIDATE_READ_OWN, CANDIDATE_READ_ASSIGNED, CANDIDATE_READ_ALL,
    PIPELINE_MANAGE, INTERVIEW_MANAGE, INTERVIEW_READ_ASSIGNED, EVALUATION_SUBMIT,
    OFFER_READ_OWN, OFFER_RESPOND, OFFER_MANAGE, OFFER_APPROVE,
    ONBOARDING_MANAGE, NOTIFICATION_READ_OWN, NOTIFICATION_MANAGE, REPORT_READ
}
