ALTER TABLE users ADD COLUMN IF NOT EXISTS department VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS lock_reason VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS lock_note TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS locked_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS locked_by VARCHAR(100);

ALTER TABLE requisition_assignments ADD COLUMN IF NOT EXISTS handover_required BOOLEAN NOT NULL DEFAULT FALSE;
CREATE INDEX IF NOT EXISTS idx_users_department ON users(department);
