package com.example.auth_service.dto;

import java.time.Instant;
import java.time.LocalDate;

/**
 * DTO phản hồi chi tiết yêu cầu tuyển dụng.
 */
public record RequisitionResponse(
        Long id,
        String requisitionCode,
        String title,
        Long departmentId,
        String departmentName,
        String departmentCode,
        Long jobTitleId,
        String jobTitleName,
        Integer quantity,
        String recruitmentType,
        Long salaryMin,
        Long salaryMax,
        String currency,
        String salaryExplanation,
        LocalDate neededDate,
        LocalDate targetDate,
        String jobDescription,
        String candidateRequirements,
        String benefits,
        String workLocation,
        String workingModel,
        String status,
        String reason,
        String rejectionReason,
        Long createdByUserId,
        String createdByName,
        Instant submittedAt,
        Long approvedByUserId,
        Instant approvedAt,
        Instant createdAt,
        Instant updatedAt,
        String jobTitleCode,
        Long jobTitleMinSalary,
        Long jobTitleMaxSalary,
        boolean outsideSalaryRange,
        String createdByEmail
) {
    public RequisitionResponse(
            Long id,
            String requisitionCode,
            String title,
            Long departmentId,
            String departmentName,
            String departmentCode,
            Long jobTitleId,
            String jobTitleName,
            Integer quantity,
            String recruitmentType,
            Long salaryMin,
            Long salaryMax,
            String currency,
            String salaryExplanation,
            LocalDate neededDate,
            LocalDate targetDate,
            String jobDescription,
            String candidateRequirements,
            String benefits,
            String workLocation,
            String workingModel,
            String status,
            String reason,
            String rejectionReason,
            Long createdByUserId,
            String createdByName,
            Instant submittedAt,
            Long approvedByUserId,
            Instant approvedAt,
            Instant createdAt,
            Instant updatedAt
    ) {
        this(id, requisitionCode, title, departmentId, departmentName, departmentCode, jobTitleId,
                jobTitleName, quantity, recruitmentType, salaryMin, salaryMax, currency, salaryExplanation,
                neededDate, targetDate, jobDescription, candidateRequirements, benefits, workLocation,
                workingModel, status, reason, rejectionReason, createdByUserId, createdByName, submittedAt,
                approvedByUserId, approvedAt, createdAt, updatedAt, null, null, null, false, null);
    }

    public RequisitionResponse(
            Long id,
            String requisitionCode,
            String title,
            Long departmentId,
            String departmentName,
            String departmentCode,
            Long jobTitleId,
            String jobTitleName,
            String jobTitleCode,
            Long jobTitleMinSalary,
            Long jobTitleMaxSalary,
            Integer quantity,
            String recruitmentType,
            String reason,
            Long salaryMin,
            Long salaryMax,
            String salaryExplanation,
            LocalDate targetDate,
            LocalDate neededDate,
            boolean outsideSalaryRange,
            String jobDescription,
            String candidateRequirements,
            String status,
            Long createdByUserId,
            String createdByName,
            String createdByEmail,
            Instant createdAt,
            Instant updatedAt
    ) {
        this(id, requisitionCode, title, departmentId, departmentName, departmentCode, jobTitleId,
                jobTitleName, quantity, recruitmentType, salaryMin, salaryMax, "VND", salaryExplanation,
                neededDate, targetDate, jobDescription, candidateRequirements, null, null, null, status,
                reason, null, createdByUserId, createdByName, null, null, null, createdAt, updatedAt,
                jobTitleCode, jobTitleMinSalary, jobTitleMaxSalary, outsideSalaryRange, createdByEmail);
    }

    // Overload for backward compatibility with 19-parameter constructor
    public RequisitionResponse(
            Long id,
            String requisitionCode,
            String title,
            Long departmentId,
            String departmentName,
            Long jobTitleId,
            String jobTitleName,
            Integer quantity,
            LocalDate targetDate,
            String status,
            String reason,
            Long proposedMinSalary,
            Long proposedMaxSalary,
            String salaryExplanation,
            String jobDescription,
            String requirements,
            Long createdByUserId,
            String createdByName,
            Instant createdAt
    ) {
        this(
                id,
                requisitionCode,
                title,
                departmentId,
                departmentName,
                null,
                jobTitleId,
                jobTitleName,
                quantity,
                null,
                proposedMinSalary,
                proposedMaxSalary,
                "VND",
                salaryExplanation,
                null,
                targetDate,
                jobDescription,
                requirements,
                null,
                null,
                null,
                status,
                reason,
                null,
                createdByUserId,
                createdByName,
                null,
                null,
                null,
                createdAt,
                createdAt
        );
    }
}
